# Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.network "private_network", type: "dhcp"
    master.vm.provision "shell", path: "provision_master.sh"
  end

  config.vm.define "slave" do |slave|
    slave.vm.box = "ubuntu/trusty64"
    slave.vm.network "private_network", type: "dhcp"
    slave.vm.provision "shell", path: "provision_slave.sh"
  end
end

